eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://spring-eureka-service:8060/eureka/
spring:
  application:
    name: spring-order-service
  datasource:
         driver-class-name: com.mysql.jdbc.Driver
         url: jdbc:mysql://127.0.0.1:3306/mysql
         username: root
         password: root
server:
  port: 8063

#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000



## Mybatis 配置
mybatis:
  typeAliasesPackage: com.order.service.model #指向实体类包路径
  mapperLocations: classpath:mapper/*.xml #classpath 路径下 mapper 包下，* 代表会扫描所有 xml 文件
  config-location: classpath:mapper/config/mybatis-configuration.xml #引入分页插件